### PR TITLE
u/rowen/DM-33062: update the command sync patterns for ts_hexapod_controller 1.2.4

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by r-owen** [comment]
The tests ran against the wrong branches of ts_hexrotcomm and ts_xml. I have tested locally against the current main of both, and they pass.

**Comment by tribeiro** [comment]
you can create a branch with the same name as the working branch (`u/rowen/DM-33062`) on the repos you need and the CI will pick it up.. 

In case you are interested in having the CI passing

**Comment by r-owen** [comment]
In this case the tests will only pass if they run with main of ts_xml and ts_hexrotcomm. I'm not sure I know how to do that.

Note: I initially created this PR against the wrong base branch (and the tests ran before I realized that). But I am pretty sure the tests will fail if i re-run them.

**Review by teweitsai — APPROVED** [review]
Looks good. Thank you for this update!

**Pull request merged**
